[package]
name = "cds"
version = "0.1.0"
authors = ["Taewoo An <taewoo.an@kaist.ac.kr>"]
edition = "2018"

[dependencies]
crossbeam-epoch = "0.9.5"
crossbeam-utils = "0.8.5"
rand = "0.8.4"
either = "1.6.1"
arr_macro = "0.1.3"

[dev-dependencies]
criterion = "0.3.4"
num_cpus = "1.13.0"

[[bench]]
name = "sequential"
harness = false

[[bench]]
name = "concurrent"
harness = false
